services:
  #order-service:
  #  build: ./order-service
  #  ports:
  #    - "8082:8080"
  #  depends_on:
  #    - kafka

  #stock-service:
  #  build: ./stock-service
  #  ports:
  #    - "8081:8080"
  #  depends_on:
  #    - kafka

  stock-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock-db
    ports:
      - "5432:5432"

  email-service:
    build: ./email-service
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgresql:
    image: docker.io/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    ports:
      - "18080:8080"
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
