spring:
  application:
    name: stock-service
  kafka:
    topic:
      name: order-topic
    consumer:
      bootstrap-servers: localhost:9094
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/order-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#  profiles:
#    active: docker

jwt:
  auth:
    converter:
      resource-id: stock-service
      principal-attribute: principal_username

logging:
  level:
    org:
      springframework:
        security: DEBUG

stock-api:
  base-url:
    name: api/v1/orders

server:
  port: 8081
