spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://stock-db:5432/stock-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/order-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8080