spring:
  application:
    name: stock-service
  kafka:
    topic:
      name: order-topic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: docker
