spring:
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name:
        order-topic
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-db
    username: postgres
    password: password
